dicionário = {
    ' ': ['espaço'],
    '/': ['barra_direita'],
    '\\': ['barra_esquerda'],
    '|': ['shift_direito', 'barra_esquerda'],
    '?': ['shift_direito', 'barra_direita'],
    '[': ['colchete_esquerdo'],
    ']': ['colchete_direito'],
    '\n': ['enter'],
    '{': ['shift_esquerdo', 'colchete_esquerdo'],
    '}': ['shift_esquerdo', 'colchete_diteito'],
    '.': ['ponto'],
    ';': ['ponto_virgula'],
    ',': ['virgula'],
    "'": ['aspas'],
    '^': ['shift_esquerdo', 'til'],
    '>': ['shift_esquerdo', 'ponto'],
    ':': ['shift_esquerdo', 'ponto_virgula'],
    '<': ['shift_esquerdo', 'virgula'],
    '"': ['shift_esquerdo', 'aspas'],
    'ã': ['til', 'a'],
    'õ': ['til', 'o'],
    'â': ['til', 'shift_esquerdo', 'a'],
    'ê': ['til', 'shift_esquerdo', 'e'],
    'ô': ['til', 'shift_esquerdo', 'o'],
    '=': ['igual'],
    'á': ['agudo', 'a'],
    'é': ['agudo', 'e'],
    'í': ['agudo', 'i'],
    'ó': ['agudo', 'o'],
    'ú': ['agudo', 'u'],
    '+': ['shift_esquerdo', '='],
    'à': ['agudo', 'shift_esquerdo', 'a'],
    '_': ['shift_esquerdo', 'menos'],
    '-': ['menos'],
    '!': ['shift_esquerdo', '1'],
    '@': ['shift_direito', '2'],
    '#': ['shift_direito', '3'],
    '$': ['shift_direito', '4'],
    '%': ['shift_direito', '5'],
    '¨': ['shift_esquerdo', '6'],
    '&': ['shift_esquerdo', '7'],
    '*': ['shift_esquerdo', '8'],
    '(': ['shift_esquerdo', '9'],
    ')': ['shift_esquerdo', '0'],
    '´': ['agudo'],
    '~': ['til'],
    '`': ['shift_esquerdo', 'agudo'],
    'backspace': ['backspace']  # não deveria mas vou colocar para facilitar
}
